### ISSUE TITLE
Support inputs with units in YAML files

### ISSUE THREAD

**Issue by wtbarnes** [rice-solar-physics/hydrad_tools#24]
Many of the HYDRAD inputs require units. Currently these cannot be read/written to the yaml config file. Need to add support for this.

Could be something like:
```yaml
input_name:
  value: 10
  unit: "cm / s"
```

There would need to be a bit of wrapper code on the YAML I/O to make sure these are handled properly.
